import { normalizeGeoName } from './normalize.js';

const SUBDIVISION_LOOKUP: Record<string, Record<string, string>> = {};
const CANONICAL_NAMES: Record<string, string[]> = {};

function addRegion(region: string, entries: [string, ...string[]][]) {
  const lookup: Record<string, string> = {};
  const canonicals: string[] = [];
  for (const [canonical, ...aliases] of entries) {
    canonicals.push(canonical);
    lookup[normalizeGeoName(canonical)] = canonical;
    for (const alias of aliases) {
      lookup[normalizeGeoName(alias)] = canonical;
    }
  }
  SUBDIVISION_LOOKUP[region] = lookup;
  CANONICAL_NAMES[region] = canonicals;
}

// --- United States (50 states + DC) ---
addRegion('US', [
  ['Alabama', 'AL'],
  ['Alaska', 'AK'],
  ['Arizona', 'AZ'],
  ['Arkansas', 'AR'],
  ['California', 'CA'],
  ['Colorado', 'CO'],
  ['Connecticut', 'CT'],
  ['Delaware', 'DE'],
  ['District of Columbia', 'DC'],
  ['Florida', 'FL'],
  ['Georgia', 'GA'],
  ['Hawaii', 'HI'],
  ['Idaho', 'ID'],
  ['Illinois', 'IL'],
  ['Indiana', 'IN'],
  ['Iowa', 'IA'],
  ['Kansas', 'KS'],
  ['Kentucky', 'KY'],
  ['Louisiana', 'LA'],
  ['Maine', 'ME'],
  ['Maryland', 'MD'],
  ['Massachusetts', 'MA'],
  ['Michigan', 'MI'],
  ['Minnesota', 'MN'],
  ['Mississippi', 'MS'],
  ['Missouri', 'MO'],
  ['Montana', 'MT'],
  ['Nebraska', 'NE'],
  ['Nevada', 'NV'],
  ['New Hampshire', 'NH'],
  ['New Jersey', 'NJ'],
  ['New Mexico', 'NM'],
  ['New York', 'NY'],
  ['North Carolina', 'NC'],
  ['North Dakota', 'ND'],
  ['Ohio', 'OH'],
  ['Oklahoma', 'OK'],
  ['Oregon', 'OR'],
  ['Pennsylvania', 'PA'],
  ['Rhode Island', 'RI'],
  ['South Carolina', 'SC'],
  ['South Dakota', 'SD'],
  ['Tennessee', 'TN'],
  ['Texas', 'TX'],
  ['Utah', 'UT'],
  ['Vermont', 'VT'],
  ['Virginia', 'VA'],
  ['Washington', 'WA'],
  ['West Virginia', 'WV'],
  ['Wisconsin', 'WI'],
  ['Wyoming', 'WY'],
]);

// --- China ---
addRegion('CN', [
  ['Anhui'],
  ['Beijing'],
  ['Chongqing'],
  ['Fujian'],
  ['Gansu'],
  ['Guangdong'],
  ['Guangxi'],
  ['Guizhou'],
  ['Hainan'],
  ['Hebei'],
  ['Heilongjiang'],
  ['Henan'],
  ['Hubei'],
  ['Hunan'],
  ['Jiangsu'],
  ['Jiangxi'],
  ['Jilin'],
  ['Liaoning'],
  ['Nei Mongol', 'Inner Mongolia'],
  ['Ningxia Hui', 'Ningxia'],
  ['Qinghai'],
  ['Shaanxi'],
  ['Shandong'],
  ['Shanghai'],
  ['Shanxi'],
  ['Sichuan'],
  ['Tianjin'],
  ['Xinjiang Uygur', 'Xinjiang'],
  ['Xizang', 'Tibet'],
  ['Yunnan'],
  ['Zhejiang'],
]);

// --- Australia ---
addRegion('AU', [
  ['Australian Capital Territory', 'ACT'],
  ['New South Wales', 'NSW'],
  ['Northern Territory', 'NT'],
  ['Queensland', 'QLD'],
  ['South Australia', 'SA'],
  ['Tasmania', 'TAS'],
  ['Victoria', 'VIC'],
  ['Western Australia', 'WA'],
]);

// --- India ---
addRegion('IN', [
  ['Andaman and Nicobar'],
  ['Andhra Pradesh'],
  ['Arunachal Pradesh'],
  ['Assam'],
  ['Bihar'],
  ['Chandigarh'],
  ['Chhattisgarh'],
  ['Dadra and Nagar Haveli'],
  ['Daman and Diu'],
  ['Delhi'],
  ['Goa'],
  ['Gujarat'],
  ['Haryana'],
  ['Himachal Pradesh'],
  ['Jammu and Kashmir'],
  ['Jharkhand'],
  ['Karnataka'],
  ['Kerala'],
  ['Lakshadweep'],
  ['Madhya Pradesh'],
  ['Maharashtra'],
  ['Manipur'],
  ['Meghalaya'],
  ['Mizoram'],
  ['Nagaland'],
  ['Orissa', 'Odisha'],
  ['Puducherry', 'Pondicherry'],
  ['Punjab'],
  ['Rajasthan'],
  ['Sikkim'],
  ['Tamil Nadu'],
  ['Tripura'],
  ['Uttar Pradesh'],
  ['Uttaranchal', 'Uttarakhand'],
  ['West Bengal'],
]);

// --- Brazil ---
addRegion('BR', [
  ['Acre', 'AC'],
  ['Alagoas', 'AL'],
  ['Amapá', 'AP'],
  ['Amazonas', 'AM'],
  ['Bahia', 'BA'],
  ['Ceará', 'CE'],
  ['Distrito Federal', 'DF'],
  ['Espírito Santo', 'ES'],
  ['Goiás', 'GO'],
  ['Maranhão', 'MA'],
  ['Mato Grosso', 'MT'],
  ['Mato Grosso do Sul', 'MS'],
  ['Minas Gerais', 'MG'],
  ['Pará', 'PA'],
  ['Paraíba', 'PB'],
  ['Paraná', 'PR'],
  ['Pernambuco', 'PE'],
  ['Piauí', 'PI'],
  ['Rio de Janeiro', 'RJ'],
  ['Rio Grande do Norte', 'RN'],
  ['Rio Grande do Sul', 'RS'],
  ['Rondônia', 'RO'],
  ['Roraima', 'RR'],
  ['Santa Catarina', 'SC'],
  ['São Paulo', 'SP'],
  ['Sergipe', 'SE'],
  ['Tocantins', 'TO'],
]);

// --- Canada ---
addRegion('CA', [
  ['Alberta', 'AB'],
  ['British Columbia', 'BC'],
  ['Manitoba', 'MB'],
  ['New Brunswick', 'NB'],
  ['Newfoundland and Labrador', 'NL'],
  ['Northwest Territories', 'NT'],
  ['Nova Scotia', 'NS'],
  ['Nunavut', 'NU'],
  ['Ontario', 'ON'],
  ['Prince Edward Island', 'PE', 'PEI'],
  ['Québec', 'QC', 'Quebec'],
  ['Saskatchewan', 'SK'],
  ['Yukon', 'YT'],
]);

// --- United Kingdom ---
addRegion('GB', [
  ['England'],
  ['Scotland'],
  ['Wales'],
  ['Northern Ireland'],
  ['London'],
  ['Edinburgh'],
  ['Glasgow'],
  ['Cardiff'],
  ['Belfast'],
  ['Manchester'],
  ['Birmingham'],
  ['Liverpool'],
  ['Leeds'],
  ['Bristol'],
  ['Sheffield'],
  ['Newcastle'],
  ['Nottingham'],
  ['Aberdeen'],
  ['Dundee'],
  ['Hampshire'],
  ['Kent'],
  ['Essex'],
  ['Devon'],
  ['Cornwall'],
  ['Norfolk'],
  ['Suffolk'],
  ['Surrey'],
  ['Oxfordshire'],
  ['Cambridgeshire'],
  ['Lancashire'],
  ['North Yorkshire', 'Yorkshire'],
  ['Merseyside'],
]);

// --- Germany ---
addRegion('DE', [
  ['Bayern'],
  ['Berlin'],
  ['Brandenburg'],
  ['Bremen'],
  ['Hamburg'],
  ['Mecklenburg-Vorpommern'],
  ['Saarland'],
  ['Schleswig-Holstein'],
  ['Thüringen', 'Thuringia'],
  ['Arnsberg'],
  ['Braunschweig'],
  ['Chemnitz'],
  ['Darmstadt'],
  ['Dessau'],
  ['Detmold'],
  ['Dresden'],
  ['Düsseldorf', 'Dusseldorf'],
  ['Freiburg'],
  ['Gießen'],
  ['Halle'],
  ['Hannover'],
  ['Karlsruhe'],
  ['Kassel'],
  ['Koblenz'],
  ['Köln', 'Cologne'],
  ['Leipzig'],
  ['Luneburg'],
  ['Magdeburg'],
  ['Mittelfranken'],
  ['Munster'],
  ['Niederbayern'],
  ['Oberbayern', 'Bavaria', 'Munich'],
  ['Oberfranken'],
  ['Oberpfalz'],
  ['Rheinhessen-Pfalz'],
  ['Schwaben'],
  ['Stuttgart'],
  ['Trier'],
  ['Tübingen'],
  ['Unterfranken'],
  ['Weser-Ems'],
]);

// --- France (pre-2016 regions) ---
addRegion('FR', [
  ['Alsace'],
  ['Aquitaine'],
  ['Auvergne'],
  ['Basse-Normandie', 'Normandy'],
  ['Bourgogne', 'Burgundy'],
  ['Bretagne', 'Brittany'],
  ['Centre'],
  ['Champagne-Ardenne'],
  ['Corse', 'Corsica'],
  ['Franche-Comté'],
  ['Haute-Normandie'],
  ['Languedoc-Roussillon'],
  ['Limousin'],
  ['Lorraine'],
  ['Midi-Pyrénées'],
  ['Nord-Pas-de-Calais'],
  ['Pays de la Loire'],
  ['Picardie'],
  ['Poitou-Charentes'],
  ["Provence-Alpes-Côte-d'Azur", 'Provence', 'PACA'],
  ['Rhône-Alpes'],
  ['Île-de-France', 'Paris'],
]);

// --- Japan ---
addRegion('JP', [
  ['Aichi'],
  ['Akita'],
  ['Aomori'],
  ['Chiba'],
  ['Ehime'],
  ['Fukui'],
  ['Fukuoka'],
  ['Fukushima'],
  ['Gifu'],
  ['Gunma'],
  ['Hiroshima'],
  ['Hokkaido'],
  ['Hyogo'],
  ['Ibaraki'],
  ['Ishikawa'],
  ['Iwate'],
  ['Kagawa'],
  ['Kagoshima'],
  ['Kanagawa'],
  ['Kochi'],
  ['Kumamoto'],
  ['Kyoto'],
  ['Mie'],
  ['Miyagi'],
  ['Miyazaki'],
  ['Nagano'],
  ['Naoasaki', 'Nagasaki'],
  ['Nara'],
  ['Niigata'],
  ['Oita'],
  ['Okayama'],
  ['Okinawa'],
  ['Osaka'],
  ['Saga'],
  ['Saitama'],
  ['Shiga'],
  ['Shimane'],
  ['Shizuoka'],
  ['Tochigi'],
  ['Tokushima'],
  ['Tokyo'],
  ['Tottori'],
  ['Toyama'],
  ['Wakayama'],
  ['Yamagata'],
  ['Yamaguchi'],
  ['Yamanashi'],
]);

// --- Mexico ---
addRegion('MX', [
  ['Aguascalientes'],
  ['Baja California'],
  ['Baja California Sur'],
  ['Campeche'],
  ['Chiapas'],
  ['Chihuahua'],
  ['Coahuila'],
  ['Colima'],
  ['Distrito Federal', 'Mexico City', 'CDMX'],
  ['Durango'],
  ['Guanajuato'],
  ['Guerrero'],
  ['Hidalgo'],
  ['Jalisco'],
  ['Michoacán', 'Michoacan'],
  ['Morelos'],
  ['México', 'Estado de Mexico', 'State of Mexico'],
  ['Nayarit'],
  ['Nuevo León', 'Nuevo Leon'],
  ['Oaxaca'],
  ['Puebla'],
  ['Querétaro', 'Queretaro'],
  ['Quintana Roo'],
  ['San Luis Potosí', 'San Luis Potosi'],
  ['Sinaloa'],
  ['Sonora'],
  ['Tabasco'],
  ['Tamaulipas'],
  ['Tlaxcala'],
  ['Veracruz'],
  ['Yucatán', 'Yucatan'],
  ['Zacatecas'],
]);

// --- Russia ---
addRegion('RU', [
  ['Adygey', 'Adygea'],
  ['Altay', 'Altai Krai'],
  ['Amur'],
  ["Arkhangel'sk", 'Arkhangelsk'],
  ["Astrakhan'", 'Astrakhan'],
  ['Bashkortostan', 'Bashkiria'],
  ['Belgorod'],
  ['Bryansk'],
  ['Buryat', 'Buryatia'],
  ['Chechnya', 'Chechen'],
  ['Chelyabinsk'],
  ['Chita'],
  ['Chukchi Autonomous Okrug', 'Chukotka'],
  ['Chuvash', 'Chuvashia'],
  ['City of St. Petersburg', 'St Petersburg', 'Saint Petersburg'],
  ['Dagestan'],
  ['Gorno-Altay', 'Altai Republic'],
  ['Ingush', 'Ingushetia'],
  ['Irkutsk'],
  ['Ivanovo'],
  ['Kabardin-Balkar', 'Kabardino-Balkaria'],
  ['Kaliningrad'],
  ['Kalmyk', 'Kalmykia'],
  ['Kaluga'],
  ['Kamchatka'],
  ['Karachay-Cherkess', 'Karachay-Cherkessia'],
  ['Karelia'],
  ['Kemerovo'],
  ['Khabarovsk'],
  ['Khakass', 'Khakassia'],
  ['Khanty-Mansiy', 'Khanty-Mansi'],
  ['Kirov'],
  ['Komi'],
  ['Kostroma'],
  ['Krasnodar'],
  ['Krasnoyarsk'],
  ['Kurgan'],
  ['Kursk'],
  ['Leningrad'],
  ['Lipetsk'],
  ['Maga Buryatdan'],
  ['Mariy-El', 'Mari El'],
  ['Mordovia'],
  ['Moskovsskaya', 'Moscow Oblast'],
  ['Moskva', 'Moscow'],
  ['Murmansk'],
  ['Nenets'],
  ['Nizhegorod', 'Nizhny Novgorod'],
  ['North Ossetia', 'North Ossetia-Alania'],
  ['Novgorod'],
  ['Novosibirsk'],
  ['Omsk'],
  ['Orel'],
  ['Orenburg'],
  ['Penza'],
  ["Perm'", 'Perm'],
  ["Primor'ye", 'Primorsky', 'Primorsky Krai'],
  ['Pskov'],
  ['Rostov'],
  ["Ryazan'", 'Ryazan'],
  ['Sakha (Yakutia)', 'Yakutia', 'Sakha'],
  ['Sakhalin'],
  ['Samara'],
  ['Saratov'],
  ['Smolensk'],
  ["Stavropol'", 'Stavropol'],
  ['Sverdlovsk'],
  ['Tambov'],
  ['Tatarstan'],
  ['Tomsk'],
  ['Tula'],
  ['Tuva'],
  ["Tver'", 'Tver'],
  ["Tyumen'", 'Tyumen'],
  ['Udmurt', 'Udmurtia'],
  ["Ul'yanovsk", 'Ulyanovsk'],
  ['Vladimir'],
  ['Volgograd'],
  ['Vologda'],
  ['Voronezh'],
  ['Yamal-Nenets'],
  ["Yaroslavl'", 'Yaroslavl'],
  ['Yevrey', 'Jewish Autonomous Oblast'],
]);

// --- Italy ---
addRegion('IT', [
  ['Abruzzo'],
  ['Apulia', 'Puglia'],
  ['Basilicata'],
  ['Calabria'],
  ['Campania'],
  ['Emilia-Romagna'],
  ['Friuli-Venezia Giulia', 'Friuli'],
  ['Lazio', 'Rome'],
  ['Liguria'],
  ['Lombardia', 'Lombardy'],
  ['Marche'],
  ['Molise'],
  ['Piemonte', 'Piedmont'],
  ['Sardegna', 'Sardinia'],
  ['Sicily', 'Sicilia'],
  ['Toscana', 'Tuscany'],
  ['Trentino-Alto Adige', 'Trentino', 'South Tyrol'],
  ['Umbria'],
  ["Valle d'Aosta", 'Aosta Valley'],
  ['Veneto'],
]);

// --- Spain ---
addRegion('ES', [
  ['Andalucía', 'Andalusia', 'Andalucia'],
  ['Aragón', 'Aragon'],
  ['Cantabria'],
  ['Castilla y León', 'Castile and Leon', 'Castilla y Leon'],
  ['Castilla-La Mancha'],
  ['Cataluña', 'Catalonia', 'Catalunya'],
  ['Ceuta y Melilla'],
  ['Comunidad Foral de Navarra', 'Navarra', 'Navarre'],
  ['Comunidad Valenciana', 'Valencia'],
  ['Comunidad de Madrid', 'Madrid'],
  ['Extremadura'],
  ['Galicia'],
  ['Islas Baleares', 'Balearic Islands'],
  ['Islas Canarias', 'Canary Islands'],
  ['La Rioja'],
  ['País Vasco', 'Basque Country', 'Pais Vasco'],
  ['Principado de Asturias', 'Asturias'],
  ['Región de Murcia', 'Murcia', 'Region de Murcia'],
]);

// --- South Korea ---
addRegion('KR', [
  ['Busan'],
  ['Daegu'],
  ['Daejeon'],
  ['Gangwon'],
  ['Gwangju'],
  ['Gyeonggi'],
  ['Incheon'],
  ['Jeju'],
  ['North Chungcheong', 'Chungcheongbuk-do'],
  ['North Gyeongsang', 'Gyeongsangbuk-do'],
  ['North Jeolla', 'Jeollabuk-do'],
  ['Sejong'],
  ['Seoul'],
  ['South Chungcheong', 'Chungcheongnam-do'],
  ['South Gyeongsang', 'Gyeongsangnam-do'],
  ['South Jeolla', 'Jeollanam-do'],
  ['Ulsan'],
]);

// --- South Africa ---
addRegion('ZA', [
  ['Eastern Cape'],
  ['Free State'],
  ['Gauteng'],
  ['KwaZulu-Natal', 'KZN'],
  ['Limpopo'],
  ['Mpumalanga'],
  ['North West'],
  ['Northern Cape'],
  ['Western Cape'],
]);

// --- Colombia ---
addRegion('CO', [
  ['Amazonas'],
  ['Antioquia'],
  ['Arauca'],
  ['Atlántico', 'Atlantico'],
  ['Bolívar', 'Bolivar'],
  ['Boyacá', 'Boyaca'],
  ['Caldas'],
  ['Caquetá', 'Caqueta'],
  ['Casanare'],
  ['Cauca'],
  ['Cesar'],
  ['Chocó', 'Choco'],
  ['Córdoba', 'Cordoba'],
  ['Cundinamarca'],
  ['Guainía', 'Guainia'],
  ['Guaviare'],
  ['Huila'],
  ['La Guajira'],
  ['Magdalena'],
  ['Meta'],
  ['Nariño', 'Narino'],
  ['Norte de Santander'],
  ['Putumayo'],
  ['Quindío', 'Quindio'],
  ['Risaralda'],
  ['San Andrés y Providencia', 'San Andres'],
  ['Santander'],
  ['Sucre'],
  ['Tolima'],
  ['Valle del Cauca'],
  ['Vaupés', 'Vaupes'],
  ['Vichada'],
]);

// --- Argentina ---
addRegion('AR', [
  ['Buenos Aires'],
  ['Catamarca'],
  ['Chaco'],
  ['Chubut'],
  ['Ciudad de Buenos Aires', 'CABA'],
  ['Córdoba', 'Cordoba'],
  ['Corrientes'],
  ['Entre Ríos', 'Entre Rios'],
  ['Formosa'],
  ['Jujuy'],
  ['La Pampa'],
  ['La Rioja'],
  ['Mendoza'],
  ['Misiones'],
  ['Neuquén', 'Neuquen'],
  ['Río Negro', 'Rio Negro'],
  ['Salta'],
  ['San Juan'],
  ['San Luis'],
  ['Santa Cruz'],
  ['Santa Fe'],
  ['Santiago del Estero'],
  ['Tierra del Fuego'],
  ['Tucumán', 'Tucuman'],
]);

export function resolveSubdivisionName(region: string, input: string): string | undefined {
  const lookup = SUBDIVISION_LOOKUP[region.toUpperCase()];
  if (!lookup) return undefined;
  return lookup[normalizeGeoName(input)];
}

export function getSubdivisionNames(region: string): string[] {
  return CANONICAL_NAMES[region.toUpperCase()] ?? [];
}
